# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Research"
  identifier = "research"
  weight = 20

[[main]]
  name = "Overview"
  url = "research"
  parent = "research"
  weight = 10


[[main]]
  name = "Publications"
  url = "publication"
  parent = "research"
  weight = 20

[[main]]
  name = "Talks & Posters"
  url = "talk"
  parent = "research"
  weight = 30

[[main]]
  name = "People"
  identifier = "people"
  weight = 30

[[main]]
  name = "Martin Gärttner"
  url = "author/martin-garttner"
  parent = "people"
  weight = 10
  
[[main]]
  name = "Group members"
  url = "people"
  parent = "people"
  weight = 20
 
[[main]]
  name = "Collaborators"
  url = "people#collaboration"
  parent = "people"
  weight = 30

[[main]]
  name = "Alumni"
  url = "people#alumni"
  parent = "people"
  weight = 40


[[main]]
  name = "Teaching"
  url = "teaching"
  weight = 40

[[main]]
  name = "Blog"
  url = "post"
  weight = 50

[[main]]
  name = "Funding"
  url = "funding"
  weight = 60
